### ISSUE TITLE
SegFault

### ISSUE THREAD

**Issue by tecosaur** [Izumemori/muscord-cpp#2]
Unfortunately, I've just tried to build this and experienced a segfault.

```
❯ muscord
free(): invalid pointer
[1]    19501 segmentation fault (core dumped)  muscord
```

I'm hoping you'll be able to help me get this working again :smiley: 

#### System Info
- **os** OpenSuse Tumbleweed
- **gcc** 10.2.1
- **playerctl** 10.2.1

<details>
    <summary>Cmake log</summary>

```
21:52:32 ❯ cmake .. -DCMAKE_INSTALL_PREFIX=. -DDEBUG=ON
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for discord-rpc source files
-- Looking for discord-rpc source files - found
-- Looking for yaml-cpp source files
-- Looking for yaml-cpp source files - found
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Checking for module 'playerctl'
--   Found playerctl, version 2.0.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tec/.local/lib/muscord-cpp/build
```

</details>

<details>
    <summary>Make log</summary>

```
21:53:07 ❯ make
Scanning dependencies of target yaml-cpp
[  2%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
[  4%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o
[  6%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o
[  8%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o
In file included from /home/tec/.local/lib/muscord-cpp/yaml-cpp/include/yaml-cpp/node/convert.h:20,
                 from /home/tec/.local/lib/muscord-cpp/yaml-cpp/src/convert.cpp:3:
/home/tec/.local/lib/muscord-cpp/yaml-cpp/include/yaml-cpp/node/impl.h: In member function ‘YAML::Node& YAML::Node::operator=(const T&)’:
/home/tec/.local/lib/muscord-cpp/yaml-cpp/include/yaml-cpp/node/impl.h:206:10: warning: ‘operator=’ should return a reference to ‘*this’ [-Weffc++]
  206 |   return *this;
      |          ^~~~~
[ 10%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/depthguard.cpp.o
[ 12%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/directives.cpp.o
[ 14%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emit.cpp.o
[ 17%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitfromevents.cpp.o
[ 19%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitter.cpp.o
[ 21%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterstate.cpp.o
[ 23%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterutils.cpp.o
[ 25%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/exceptions.cpp.o
[ 27%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/exp.cpp.o
[ 29%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/memory.cpp.o
[ 31%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node.cpp.o
[ 34%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node_data.cpp.o
[ 36%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodebuilder.cpp.o
In file included from /home/tec/.local/lib/muscord-cpp/yaml-cpp/src/nodebuilder.cpp:5:
/home/tec/.local/lib/muscord-cpp/yaml-cpp/include/yaml-cpp/node/impl.h: In member function ‘YAML::Node& YAML::Node::operator=(const T&)’:
/home/tec/.local/lib/muscord-cpp/yaml-cpp/include/yaml-cpp/node/impl.h:206:10: warning: ‘operator=’ should return a reference to ‘*this’ [-Weffc++]
  206 |   return *this;
      |          ^~~~~
[ 38%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodeevents.cpp.o
[ 40%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/null.cpp.o
[ 42%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/ostream_wrapper.cpp.o
[ 44%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parse.cpp.o
In file included from /home/tec/.local/lib/muscord-cpp/yaml-cpp/src/parse.cpp:7:
/home/tec/.local/lib/muscord-cpp/yaml-cpp/include/yaml-cpp/node/impl.h: In member function ‘YAML::Node& YAML::Node::operator=(const T&)’:
/home/tec/.local/lib/muscord-cpp/yaml-cpp/include/yaml-cpp/node/impl.h:206:10: warning: ‘operator=’ should return a reference to ‘*this’ [-Weffc++]
  206 |   return *this;
      |          ^~~~~
[ 46%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parser.cpp.o
[ 48%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/regex_yaml.cpp.o
[ 51%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanner.cpp.o
[ 53%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanscalar.cpp.o
[ 55%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantag.cpp.o
[ 57%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantoken.cpp.o
[ 59%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/simplekey.cpp.o
[ 61%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/singledocparser.cpp.o
[ 63%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/stream.cpp.o
[ 65%] Building CXX object yaml-cpp/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o
[ 68%] Linking CXX static library libyaml-cpp.a
[ 68%] Built target yaml-cpp
Scanning dependencies of target discord-rpc
[ 70%] Building CXX object discord-rpc/src/CMakeFiles/discord-rpc.dir/discord_rpc.cpp.o
[ 72%] Building CXX object discord-rpc/src/CMakeFiles/discord-rpc.dir/rpc_connection.cpp.o
In file included from /home/tec/.local/lib/muscord-cpp/discord-rpc/src/serialization.h:15,
                 from /home/tec/.local/lib/muscord-cpp/discord-rpc/src/rpc_connection.h:4,
                 from /home/tec/.local/lib/muscord-cpp/discord-rpc/src/rpc_connection.cpp:1:
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h: In instantiation of ‘void rapidjson::GenericValue<Encoding, Allocator>::SetObjectRaw(rapidjson::GenericValue<Encoding, Allocator>::Member*, rapidjson::SizeType, Allocator&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::GenericValue<Encoding, Allocator>::Member = rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >; rapidjson::SizeType = unsigned int]’:
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2363:55:   required from ‘bool rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::EndObject(rapidjson::SizeType) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::SizeType = unsigned int]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:1736:40:   required from ‘rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Transit(rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:1832:58:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:487:46:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2159:57:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; SourceEncoding = rapidjson::UTF8<>; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2175:62:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2200:58:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch*) [with unsigned int parseFlags = 0; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2208:47:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/src/rpc_connection.cpp:111:50:   required from here
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:1952:24: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘rapidjson::GenericValue<rapidjson::UTF8<> >::Member’ {aka ‘struct rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >’} with no trivial copy-assignment; use copy-assignment instead [-Wclass-memaccess]
 1952 |             std::memcpy(m, members, count * sizeof(Member));
      |             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/tec/.local/lib/muscord-cpp/discord-rpc/src/serialization.h:15,
                 from /home/tec/.local/lib/muscord-cpp/discord-rpc/src/rpc_connection.h:4,
                 from /home/tec/.local/lib/muscord-cpp/discord-rpc/src/rpc_connection.cpp:1:
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:71:8: note: ‘rapidjson::GenericValue<rapidjson::UTF8<> >::Member’ {aka ‘struct rapidjson::GenericMember<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<> >’} declared here
   71 | struct GenericMember {
      |        ^~~~~~~~~~~~~
In file included from /home/tec/.local/lib/muscord-cpp/discord-rpc/src/serialization.h:15,
                 from /home/tec/.local/lib/muscord-cpp/discord-rpc/src/rpc_connection.h:4,
                 from /home/tec/.local/lib/muscord-cpp/discord-rpc/src/rpc_connection.cpp:1:
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h: In instantiation of ‘void rapidjson::GenericValue<Encoding, Allocator>::SetArrayRaw(rapidjson::GenericValue<Encoding, Allocator>*, rapidjson::SizeType, Allocator&) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; rapidjson::SizeType = unsigned int]’:
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2371:54:   required from ‘bool rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::EndArray(rapidjson::SizeType) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::SizeType = unsigned int]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:1766:39:   required from ‘rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Transit(rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Token, rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParsingState, InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:1832:58:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::IterativeParse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/reader.h:487:46:   required from ‘rapidjson::ParseResult rapidjson::GenericReader<SourceEncoding, TargetEncoding, StackAllocator>::Parse(InputStream&, Handler&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Handler = rapidjson::GenericDocument<rapidjson::UTF8<>, rapidjson::MemoryPoolAllocator<>, FixedLinearAllocator<2048> >; SourceEncoding = rapidjson::UTF8<>; TargetEncoding = rapidjson::UTF8<>; StackAllocator = FixedLinearAllocator<2048>]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2159:57:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; SourceEncoding = rapidjson::UTF8<>; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2175:62:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseStream(InputStream&) [with unsigned int parseFlags = 1; InputStream = rapidjson::GenericInsituStringStream<rapidjson::UTF8<> >; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2200:58:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch*) [with unsigned int parseFlags = 0; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:2208:47:   required from ‘rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>& rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::ParseInsitu(rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch*) [with Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>; StackAllocator = FixedLinearAllocator<2048>; rapidjson::GenericDocument<Encoding, Allocator, StackAllocator>::Ch = char]’
/home/tec/.local/lib/muscord-cpp/discord-rpc/src/rpc_connection.cpp:111:50:   required from here
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:1939:24: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
 1939 |             std::memcpy(e, values, count * sizeof(GenericValue));
      |             ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tec/.local/lib/muscord-cpp/discord-rpc/thirdparty/rapidjson-1.1.0/include/rapidjson/document.h:540:7: note: ‘class rapidjson::GenericValue<rapidjson::UTF8<> >’ declared here
  540 | class GenericValue {
      |       ^~~~~~~~~~~~
cc1plus: note: unrecognized command-line option ‘-Wno-global-constructors’ may hcc1plus: note: unrecognized command-line option ‘-Wno-exit-time-destructors’ maycc1plus: note: unrecognized command-line option ‘-Wno-covered-switch-default’ macc1plus: note: unrecognized command-line option ‘-Wno-c++98-compat-pedantic’ maycc1plus: note: unrecognized command-line option ‘-Wno-c++98-compat’ may have bee[ 74%] Building CXX object discord-rpc/src/CMakeFiles/discord-rpc.dir/serializat[ 76%] Building CXX object discord-rpc/src/CMakeFiles/discord-rpc.dir/connection[ 78%] Building CXX object discord-rpc/src/CMakeFiles/discord-rpc.dir/discord_re[ 80%] Linking CXX static library libdiscord-rpc.a
[ 80%] Built target discord-rpc
Scanning dependencies of target muscord
[ 82%] Building CXX object CMakeFiles/muscord.dir/src/common.cpp.o
[ 85%] Building CXX object CMakeFiles/muscord.dir/src/main.cpp.o
[ 87%] Building CXX object CMakeFiles/muscord.dir/src/muscord.cpp.o
[ 89%] Building CXX object CMakeFiles/muscord.dir/src/muscord_config.cpp.o
[ 91%] Building CXX object CMakeFiles/muscord.dir/src/muscord_events.cpp.o
[ 93%] Building CXX object CMakeFiles/muscord.dir/src/muscord_rpc.cpp.o
[ 95%] Building CXX object CMakeFiles/muscord.dir/src/muscord_state.cpp.o
[ 97%] Building CXX object CMakeFiles/muscord.dir/src/playerctl.cpp.o
[100%] Linking CXX executable bin/muscord
[100%] Built target muscord
```

</details>

**Comment by Izumemori** [comment]
I think it's because of this: https://github.com/Izumemori/muscord-cpp/blob/49cb50dc5ed17023b0c91f1699a9e9832b591bb5/src/muscord_rpc.cpp#L62-L71

but just to make sure could you compile with debug symbols and run it in gdb to figure out where the unnecessary free is?

I'll get around to fixing that later.

**Comment by tecosaur** [comment]
Maybe not actually, this is what I got:
```
Reading symbols from /home/tec/.local/bin/muscord...
(gdb) run
Starting program: /home/tec/.local/bin/muscord
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
free(): invalid pointer

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	  return ret;
(gdb) l
44	
45	  int ret = INLINE_SYSCALL_CALL (tgkill, pid, tid, sig);
46	
47	  __libc_signal_restore_set (&set);
48	
49	  return ret;
50	}
51	libc_hidden_def (raise)
52	weak_alias (raise, gsignal)
```

**Comment by tecosaur** [comment]
First time using `gdb`, but I have a little more
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff78f0538 in __GI_abort () at abort.c:79
#2  0x00007ffff7949177 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7a59b90 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7950bcc in malloc_printerr (str=str@entry=0x7ffff7a57d7d "free(): invalid pointer") at malloc.c:5389
#4  0x00007ffff7951f9c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:4201
#5  0x00000000004c8ef4 in muscord::get_config_dir[abi:cxx11]() ()
#6  0x00000000004cae64 in main ()
```

**Comment by tecosaur** [comment]
No ideas I'm guessing?

**Comment by Izumemori** [comment]
Sorry it took so long, I've been incredibly busy with Uni and stopped using this myself
